version: '3.9'
services:
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  apollo:
    build: .
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    links:
      - postgres
