version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /db/var/lib/postgresql:/var/lib/postgresql

  apollo:
    container_name: apollo
    image: ghcr.io/pt-hieu/lettutor-crm:apollo
    depends_on:
      - postgres
    ports:
      - '8000:8000'
