version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - 'pt-hieu'
    reviewers:
      - 'pt-hieu'
    commit-message:
      prefix: 'deps'
      include: 'scope'
      
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    assignees:
      - 'pt-hieu'
    reviewers:
      - 'pt-hieu'
    commit-message:
      prefix: 'deps'
      include: 'scope'
