export enum Actions {
  // ====================== ADMIN ====
  IS_ADMIN = 'Can do anything',
  VIEW_ALL_USERS = 'Can view all users',
  VIEW_ALL_USER_DETAILS = 'Can view any user details',
  EDIT_USER_STATUS = 'Can edit any user status',
  CREATE_NEW_USER = 'Can create new user',
  EDIT_ROLE = 'Can edit any roles',
  DELETE_ROLE = 'Can delete any roles',
  CREATE_NEW_ROLE = 'Can create new role',
  VIEW_ALL_LEADS = 'Can view all leads',
  VIEW_ALL_LEAD_DETAILS = 'Can view any lead details',
  EDIT_ALL_LEADS = 'Can edit any leads',
  CREATE_NEW_LEAD = 'Can create new lead',
  CONVERT_LEAD = 'Can convert any leads',
  VIEW_ALL_CONTACTS = 'Can view all contacts',
  VIEW_ALL_CONTACT_DETAILS = 'Can view any contact details',
  EDIT_ALL_CONTACTS = 'Can edit any contacts',
  CREATE_NEW_CONTACT = 'Can create new contacts',
  VIEW_ALL_ACCOUNTS = 'Can view all accounts',
  VIEW_ALL_ACCOUNT_DETAILS = 'Can view any account details',
  EDIT_ALL_ACCOUNTS = 'Can edit any accounts',
  CREATE_NEW_ACCOUNT = 'Can create new account',
  VIEW_ALL_DEALS = 'Can view all deals',
  VIEW_ALL_DEAL_DETAILS = 'Can view any deal details',
  EDIT_ALL_DEALS = 'Can edit any deals',
  CREATE_NEW_DEAL = 'Can create new deal',
  VIEW_ALL_TASKS = 'Can view all tasks',
  VIEW_ALL_TASK_DETAILS = 'Can view any task details',
  EDIT_ALL_TASK = 'Can edit any task',
  CREATE_NEW_TASK = 'Can create new task',
  CLOSE_TASK = 'Can close any task',
}
