version: "3.9"
services:
  postgres-poseidon:
    container_name: postgres-poseidon
    image: postgres:alpine
    ports:
      - "5433:5433"
    expose:
      - 5433
    command: -p 5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cms
      PGDATA: /data/postgres
    volumes:
      - postgres-poseidon:/data/postgres

  poseidon:
    container_name: poseidon
    image: ghcr.io/pt-hieu/lettutor-crm:poseidon
    depends_on:
      - postgres-poseidon
    environment:
      - DATABASE_HOST=postgres-poseidon
      - DATABASE_PORT=5433
    ports:
      - "1337:1337"

volumes:
  postgres-poseidon:
