version: "3.9"
services:
  postgres-poseidon:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cms
      PGDATA: /data/postgres
    volumes:
      - postgres-poseidon:/data/postgres

  apollo:
    container_name: poseidon
    image: ghcr.io/pt-hieu/lettutor-crm:poseidon
    depends_on:
      - postgres-poseidon
    ports:
      - "1337:1337"

volumes:
  postgres-poseidon:
