version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres

  apollo:
    container_name: apollo
    image: ghcr.io/pt-hieu/lettutor-crm:apollo-prod
    depends_on:
      - postgres
    ports:
      - '8000:8000'

volumes:
    postgres: