export const API = process.env.NEXT_PUBLIC_API
export const POSEIDON_API = process.env.NEXT_PUBLIC_POSEIDON_API

export const POSEIDON_IDENTIFIER = process.env.NEXT_PUBLIC_POSEIDON_IDENTIFIER
export const POSEIDON_PASSWORD = process.env.NEXT_PUBLIC_POSEIDON_PASSWORD

export const ARTEMIS_URL = process.env.NEXT_PUBLIC_ARTEMIS_URL
