name: Deployment

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE }}            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@18.167.61.239 '
            cd ~/lettutor-crm &&
            git pull &&
            cd ./artemis &&
            ./start.sh &&
            cd ../apollo &&
            docker-compose down && docker-compose up -d --build
          '
