name: Artemis
on:
  workflow_dispatch:
    branches: [dev]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./
          file: ./docker/Dockerfile.artemis
          push: true
          tags: ghcr.io/pt-hieu/lettutor-crm:artemis
          labels: ${{ steps.meta.outputs.labels }}

  Deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: Build
    steps:
      - uses: actions/checkout@v2
      - name: deploy on ec2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@16.162.104.246 '
            cd ~/lettutor-crm && ./start.sh artemis
          '