name: run test

on:
  pull_request:
    branches: [dev, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Change directory
        run: cd backend

      - name: Install Dependency
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run Unit Test
        run: yarn test
