name: run test

on:
  pull_request:
    branches: [dev, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run backend test
        run: |
          cd backend
          npm install
          npm run test
