name: Deploy
on:
  push:
    branches: [dev]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Get Diff On Artemis
        uses: technote-space/get-diff-action@v6.0.1
        with:
          PATTERNS: |
            artemis/**/*.{tsx,ts,js,json,jsx}
          SET_ENV_NAME: ARTEMIS_DIFF

      - name: Get Diff On Apollo
        uses: technote-space/get-diff-action@v6.0.1
        with:
          PATTERNS: |
            apollo/src/**/*.{ts}
            apollo/*.{js,json}
          SET_ENV_NAME: APOLLO_DIFF

      - name: Get Diff On Poseidon
        uses: technote-space/get-diff-action@v6.0.1
        with:
          PATTERNS: |
            poseidon/{src,config}/**/*.{js,json}
            poseidon/*.{js,json}
          SET_ENV_NAME: POSEIDON_DIFF

  apollo:
    runs-on: ubuntu-latest
    needs: check-diff
    if: env.APOLLO_DIFF
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./apollo
          push: true
          tags: ghcr.io/pt-hieu/lettutor-crm:apollo
          labels: ${{ steps.meta.outputs.labels }}

  artemis:
    runs-on: ubuntu-latest
    needs: check-diff
    if: env.ARTEMIS_DIFF
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./artemis
          push: true
          tags: ghcr.io/pt-hieu/lettutor-crm:artemis
          labels: ${{ steps.meta.outputs.labels }}

  poseidon:
    runs-on: ubuntu-latest
    needs: check-diff
    if: env.POSEIDON_DIFF
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./poseidon
          push: true
          tags: ghcr.io/pt-hieu/lettutor-crm:poseidon
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_KEY_ID }}
            AWS_ACCESS_SECRET=${{ secrets.AWS_SECRET }}
            AWS_REGION=ap-east-1
            AWS_BUCKET_NAME=strapi-dev-93427349
            AWS_S3_STORAGE_CLASS=S3 Standard

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [apollo, artemis, poseidon]
    steps:
      - uses: actions/checkout@v2
      - name: deploy on ec2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          params=()

          [[ ${{ env.APOLLO_DIFF }} ]] && params+=(apollo)
          [[ ${{ env.ARTEMIS_DIFF }} ]] && params+=(artemis)
          [[ ${{ env.POSEIDON_DIFF }} ]] && params+=(poseidon)
          
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@16.162.104.246 '
            cd ~/lettutor-crm && ./start.sh "${params[@]}"
          '
